# Generated by Django 4.0.3 on 2023-07-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('canceled', True), ('finished', 'finished'), ('created', 'created')], default='created', max_length=50),
        ),
    ]
